/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.26
 * Generated at: 2021-09-13 14:44:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class changepwd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


String fname = (String)session.getAttribute("fname");
String email = (String)session.getAttribute("email");
String pwd = (String)session.getAttribute("pwd");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("nav {\r\n");
      out.write("\tmargin: 27px auto 0;\r\n");
      out.write("\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\twidth: 510px;\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("\tbackground-color: #34495e;\r\n");
      out.write("\tborder-radius: 8px;\r\n");
      out.write("\tfont-size: 0;\r\n");
      out.write("}\r\n");
      out.write("nav a {\r\n");
      out.write("\tline-height: 50px;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tfont-size: 15px;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tz-index: 1;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\ttext-transform: uppercase;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("nav .animation {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\ttop: 0;\r\n");
      out.write("\tz-index: 0;\r\n");
      out.write("\ttransition: all .5s ease 0s;\r\n");
      out.write("\tborder-radius: 8px;\r\n");
      out.write("}\r\n");
      out.write("a:nth-child(1) {\r\n");
      out.write("\twidth: 110px;\r\n");
      out.write("}\r\n");
      out.write("a:nth-child(2) {\r\n");
      out.write("\twidth: 250px;\r\n");
      out.write("}\r\n");
      out.write("a:nth-child(3) {\r\n");
      out.write("\twidth: 150px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("nav .start-home, a:nth-child(1):hover~.animation {\r\n");
      out.write("\twidth: 110px;\r\n");
      out.write("\tleft: 0;\r\n");
      out.write("\tbackground-color:\tCrimson;\r\n");
      out.write("}\r\n");
      out.write("nav .start-about, a:nth-child(2):hover~.animation {\r\n");
      out.write("\twidth: 250px;\r\n");
      out.write("\tleft: 110px;\r\n");
      out.write("\tbackground-color:SeaGreen;\r\n");
      out.write("}\r\n");
      out.write("nav .start-blog, a:nth-child(3):hover~.animation {\r\n");
      out.write("\twidth: 150px;\r\n");
      out.write("\tleft: 360px;\r\n");
      out.write("\tbackground-color: Goldenrod;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tfont-family: sans-serif;\r\n");
      out.write("\tbackground:#BC8F8F;\r\n");
      out.write("}\r\n");
      out.write("h1 {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tmargin: 40px 0 40px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfont-size: 30px;\r\n");
      out.write("\tcolor: #ecf0f1;\r\n");
      out.write("\ttext-shadow: 2px 2px 4px #000000;\r\n");
      out.write("\tfont-family: 'Cherry Swash', cursive;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("p {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    bottom: 20px;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    color: #ecf0f1;\r\n");
      out.write("    font-family: 'Cherry Swash',cursive;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("span {\r\n");
      out.write("    color: #2BD6B4;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("@use postcss-preset-env {\r\n");
      out.write("  stage: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* helpers/align.css */\r\n");
      out.write("\r\n");
      out.write(".align {\r\n");
      out.write("  display: grid;\r\n");
      out.write("  place-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* helpers/grid.css */\r\n");
      out.write("\r\n");
      out.write(":root {\r\n");
      out.write("  --gridMaxWidth: 24em;\r\n");
      out.write("  --gridWidth: 90%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".grid {\r\n");
      out.write("  inline-size: var(--gridWidth);\r\n");
      out.write("  margin-inline: auto;\r\n");
      out.write("  max-inline-size: var(--gridMaxWidth);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* helpers/icon.css */\r\n");
      out.write("\r\n");
      out.write(".icon {\r\n");
      out.write("  block-size: 1.25em;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  inline-size: 1.25em;\r\n");
      out.write("  line-height: 1.25em;\r\n");
      out.write("  margin-right: 0.625em;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  vertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icon--info {\r\n");
      out.write("  background-color: #e5e5e5;\r\n");
      out.write("  border-radius: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* layout/base.css */\r\n");
      out.write("\r\n");
      out.write(":root {\r\n");
      out.write("  --bodyBackgroundColor: #eaeaea;\r\n");
      out.write("  --bodyColor: #999;\r\n");
      out.write("  --bodyFontFamily: 'Helvetica', 'Arial';\r\n");
      out.write("  --bodyFontFamilyFallback: sans-serif;\r\n");
      out.write("  --bodyFontSize: 0.875rem;\r\n");
      out.write("  --bodyFontWeight: 400;\r\n");
      out.write("  --bodyLineHeight: 1.5;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("*,\r\n");
      out.write("*::before,\r\n");
      out.write("*::after {\r\n");
      out.write("  box-sizing: inherit;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("html {\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* modules/anchor.css */\r\n");
      out.write("\r\n");
      out.write(":root {\r\n");
      out.write("  --anchorColor: inherit;\r\n");
      out.write("  --anchorHoverColor: #1dabb8;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("  color: var(--anchorColor);\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  transition: color 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:hover {\r\n");
      out.write("  color: var(--anchorHoverColor);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* modules/form.css */\r\n");
      out.write("\r\n");
      out.write("fieldset {\r\n");
      out.write("  border: none;\r\n");
      out.write("  margin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input {\r\n");
      out.write("  appearance: none;\r\n");
      out.write("  border: none;\r\n");
      out.write("  font: inherit;\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  outline: none;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type='submit'] {\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form input[type='email'],\r\n");
      out.write(".form input[type='password'] {\r\n");
      out.write("  inline-size: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* modules/login.css */\r\n");
      out.write("\r\n");
      out.write(":root {\r\n");
      out.write("  --loginBorderRadius: 0.25em;\r\n");
      out.write("  --loginHeaderBackgroundColor: #282830;\r\n");
      out.write("\r\n");
      out.write("  --loginInputBorderRadius: 0.25em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login__header {\r\n");
      out.write("  background-color: var(--loginHeaderBackgroundColor);\r\n");
      out.write("  border-top-left-radius: var(--loginBorderRadius);\r\n");
      out.write("  border-top-right-radius: var(--loginBorderRadius);\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  padding: 2.5em;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-transform: uppercase;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login__title {\r\n");
      out.write("  font-size: 1rem;\r\n");
      out.write("  margin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login__body {\r\n");
      out.write("  background-color: #fff;\r\n");
      out.write("  padding: 3.5em;\r\n");
      out.write("  position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login__body::before {\r\n");
      out.write("  background-color: #fff;\r\n");
      out.write("  content: '';\r\n");
      out.write("  height: 0.5em;\r\n");
      out.write("  left: 50%;\r\n");
      out.write("  margin-left: -0.25em;\r\n");
      out.write("  margin-top: -0.25em;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 0;\r\n");
      out.write("  transform: rotate(45deg);\r\n");
      out.write("  width: 0.5em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login input[type='email'],\r\n");
      out.write(".login input[type='password'] {\r\n");
      out.write("  border: 0.0625em solid #e5e5e5;\r\n");
      out.write("  padding: 1.15em 1.50em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login input[type='email'] {\r\n");
      out.write("  border-top-left-radius: var(--loginInputBorderRadius);\r\n");
      out.write("  border-top-right-radius: var(--loginInputBorderRadius);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login input[type='password'] {\r\n");
      out.write("  border-bottom-left-radius: var(--loginInputBorderRadius);\r\n");
      out.write("  border-bottom-right-radius: var(--loginInputBorderRadius);\r\n");
      out.write("  border-top: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login input[type='submit'] {\r\n");
      out.write("  background-color: crimson;\r\n");
      out.write("  border-radius: var(--loginInputBorderRadius);\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  font-weight: 700;\r\n");
      out.write("  order: 1;\r\n");
      out.write("  padding: 0.75em 1.25em;\r\n");
      out.write("  transition: background-color 0.3s;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  justify-content: center;  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login input[type='submit']:focus,\r\n");
      out.write(".login input[type='submit']:hover {\r\n");
      out.write("  background-color: crimson;\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login__footer {\r\n");
      out.write("  align-items: center;\r\n");
      out.write("  background-color: #fff;\r\n");
      out.write("  border-bottom-left-radius: var(--loginBorderRadius);\r\n");
      out.write("  border-bottom-right-radius: var(--loginBorderRadius);\r\n");
      out.write("  display: flex;\r\n");
      out.write("  justify-content: space-between;\r\n");
      out.write("  padding-bottom: 1.5em;\r\n");
      out.write("  padding-left: 1.5em;\r\n");
      out.write("  padding-right: 1.5em;\r\n");
      out.write("  justify-content: center;  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login__footer p {\r\n");
      out.write("  margin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h1 >JSP Application For JFSD Skilling-5</h1>\r\n");
      out.write("\r\n");
      out.write("<nav>\r\n");
      out.write("\t<a href=\"userhome.jsp\">Home</a>\r\n");
      out.write("\t<a href=\"changepwd.jsp\">Change Password</a>\r\n");
      out.write("\t<a href=\"ulogout.jsp\">Log Out</a>\r\n");
      out.write("\t<div class=\"animation start-home\"></div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<h1>Welcome&nbsp;&nbsp;");
      out.print(fname);
      out.write("</h1>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br><br>\r\n");
      out.write(" <div class=\"grid\">\r\n");
      out.write("\r\n");
      out.write("    <form method=\"post\" action=\"changepwd1.jsp\" class=\"form login\">\r\n");
      out.write("\r\n");
      out.write("      <header class=\"login__header\">\r\n");
      out.write("        <h3 class=\"login__title\">Update Password</h3>\r\n");
      out.write("      </header>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"login__body\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"form__field\">\r\n");
      out.write("          <input type=\"password\" placeholder=\"Old Password\" name=\"opwd\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"form__field\">\r\n");
      out.write("          <input type=\"password\" placeholder=\"New Password\" name=\"npwd\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("<div style=\"text-align:center;\">\r\n");
      out.write("      <footer class=\"login__footer\" >\r\n");
      out.write("        <input type=\"submit\"  value=\"Login\">\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("      </footer>\r\n");
      out.write("    </div>\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
