/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.26
 * Generated at: 2021-09-12 13:44:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.sql.*;
import dbconnection.DBConnection;

public final class viewusers_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("dbconnection.DBConnection");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String aid = (String)session.getAttribute("aid");
String pwd = (String)session.getAttribute("pwd");
if(aid==null || pwd==null)
{
    response.sendRedirect("asession.html");
}

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("    <style>\r\n");
      out.write("nav {\r\n");
      out.write("\tmargin: 27px auto 0;\r\n");
      out.write("\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\twidth: 510px;\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("\tbackground-color: #34495e;\r\n");
      out.write("\tborder-radius: 8px;\r\n");
      out.write("\tfont-size: 0;\r\n");
      out.write("}\r\n");
      out.write("nav a {\r\n");
      out.write("\tline-height: 50px;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tfont-size: 15px;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tz-index: 1;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\ttext-transform: uppercase;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("nav .animation {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\ttop: 0;\r\n");
      out.write("\tz-index: 0;\r\n");
      out.write("\ttransition: all .5s ease 0s;\r\n");
      out.write("\tborder-radius: 8px;\r\n");
      out.write("}\r\n");
      out.write("a:nth-child(1) {\r\n");
      out.write("\twidth: 110px;\r\n");
      out.write("}\r\n");
      out.write("a:nth-child(2) {\r\n");
      out.write("\twidth: 250px;\r\n");
      out.write("}\r\n");
      out.write("a:nth-child(3) {\r\n");
      out.write("\twidth: 150px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("nav .start-home, a:nth-child(1):hover~.animation {\r\n");
      out.write("\twidth: 110px;\r\n");
      out.write("\tleft: 0;\r\n");
      out.write("\tbackground-color:\tCrimson;\r\n");
      out.write("}\r\n");
      out.write("nav .start-about, a:nth-child(2):hover~.animation {\r\n");
      out.write("\twidth: 250px;\r\n");
      out.write("\tleft: 110px;\r\n");
      out.write("\tbackground-color:SeaGreen;\r\n");
      out.write("}\r\n");
      out.write("nav .start-blog, a:nth-child(3):hover~.animation {\r\n");
      out.write("\twidth: 150px;\r\n");
      out.write("\tleft: 360px;\r\n");
      out.write("\tbackground-color: Goldenrod;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tfont-family: sans-serif;\r\n");
      out.write("\tbackground:#BC8F8F;\r\n");
      out.write("}\r\n");
      out.write("h1 {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tmargin: 40px 0 40px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfont-size: 30px;\r\n");
      out.write("\tcolor: #ecf0f1;\r\n");
      out.write("\ttext-shadow: 2px 2px 4px #000000;\r\n");
      out.write("\tfont-family: 'Cherry Swash', cursive;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("p {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    bottom: 20px;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    color: #ecf0f1;\r\n");
      out.write("    font-family: 'Cherry Swash',cursive;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("span {\r\n");
      out.write("    color: #2BD6B4;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<h1 >JSP Application For JFSD Skilling-5</h1>\r\n");
      out.write("\r\n");
      out.write("<nav>\r\n");
      out.write("\t<a href=\"adminhome.jsp\">Home</a>\r\n");
      out.write("\t<a href=\"viewusers.jsp\">View Users</a>\r\n");
      out.write("\t<a href=\"alogout.jsp\">Log Out</a>\r\n");
      out.write("\t<div class=\"animation start-home\"></div>\r\n");
      out.write("</nav>\r\n");
      out.write("        <h1 align=center>Welcome&nbsp;&nbsp;");
      out.print(aid);
      out.write("</h1><br>\r\n");
      out.write("<table  style=\"width: 1000px; margin-left: auto; margin-right: auto;border:2px solid darkblue;\">\r\n");
      out.write("<tr align=center bgcolor=\"springgreen\" style=\"line-height: 40px;border:2px solid tomato;width: 100%;\r\n");
      out.write("    max-width: 100%;border:2px solid tomato;\">\r\n");
      out.write("<th>ID</th>\r\n");
      out.write("<th>FULL NAME</th>\r\n");
      out.write("<th>GENDER</th>\r\n");
      out.write("<th>USERNAME</th>\r\n");
      out.write("<th>EMAIL ID</th>\r\n");
      out.write("<th>MOBILE NO</th>\r\n");
      out.write("<th>ADDRESS</th>\r\n");
      out.write("<th>ACTION</th>\r\n");
      out.write("</tr>\r\n");

Connection con=DBConnection.getConnection();
 
 PreparedStatement pstmt = con.prepareStatement("select * from userreg");
ResultSet rs = pstmt.executeQuery();
 while(rs.next())
{
	
      out.write("\r\n");
      out.write("\t<tr align=center bgcolor=\"tomato\" style=\"line-height: 35px;border:2px solid springgreen;\">\r\n");
      out.write("\t<td>");
      out.print(rs.getString("id"));
      out.write("</td>\r\n");
      out.write("\t<td>");
      out.print(rs.getString("name"));
      out.write("</td>\r\n");
      out.write("\t<td>");
      out.print(rs.getString("gender"));
      out.write("</td>\r\n");
      out.write("\t<td>");
      out.print(rs.getString("username"));
      out.write("</td>\r\n");
      out.write("\t<td>");
      out.print(rs.getString("email"));
      out.write("</td>\r\n");
      out.write("\t<td>");
      out.print(rs.getString("mobile"));
      out.write("</td>\r\n");
      out.write("\t<td>");
      out.print(rs.getString("address"));
      out.write("</td>\r\n");
      out.write("\t<td>\r\n");
      out.write("\t<a href=\"deleteuser.jsp?id=");
      out.print(rs.getString("id"));
      out.write("\">Delete</a>\r\n");
      out.write("\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t");

}


      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
